services:
  postgres:
    container_name: postgres_lyceum
    image: postgres:latest
    environment:
      POSTGRES_DB: lyceum_API
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
