CREATE TABLE users(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150),
    identifier VARCHAR(20) UNIQUE NOT NULL,
    created_at DATE DEFAULT CURRENT_DATE NOT NULL
);